### ISSUE TITLE
better error msg 

### ISSUE THREAD

**Issue by sundy-li** [databendcloud/bendsql#14]
I did not auth and execute query
```
❯ bendsql query 'select 1'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1 pc=0x736ad2]

goroutine 1 [running]:
```

**Comment by hantmac** [comment]
The problem has not recurred because `bendsql query 'select 1'` will hang up just like:

<img width="376" alt="image" src="https://user-images.githubusercontent.com/7600925/192147290-bb2d1012-4076-4e39-b1a7-bddac9d48bc9.png">
